services:
    app.report_generator:
        class: AppBundle\Service\EventsReportGenerator
        arguments: ["%kernel.root_dir%", "@twig", "@knp_snappy.pdf"]

    app.summary_report_generator:
        class: AppBundle\Service\SummaryReportGenerator
        arguments: ["%kernel.root_dir%", "@twig", "@knp_snappy.pdf"]

    app.listener.change_password:
        class: AppBundle\EventListener\PasswordChangeRedirectListener
        arguments: ['@router']
        tags:
          - { name: kernel.event_subscriber }

    app.listener.login:
        class: AppBundle\EventListener\LoginListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: kernel.event_subscriber }

    app.listener.report:
        class: AppBundle\EventListener\ReportListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: kernel.event_subscriber }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
